// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoolDNSWpfApp.Models;

public partial class Attachment
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public string ObjectKey { get; set; }

    public string ContentType { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}