// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CoolDNSWpfApp.Models;

public partial class CoolDNSDBContext : DbContext
{
    public CoolDNSDBContext()
    {
    }

    public CoolDNSDBContext(DbContextOptions<CoolDNSDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseLazyLoadingProxies().UseSqlServer("Data Source=KOMP\\SQLEXPRESS;Initial Catalog=CoolDNSDB;Integrated Security=True;TrustServerCertificate=True\r\n");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Attachme__3214EC07EEAF65AC");

            entity.ToTable("Attachment");

            entity.Property(e => e.ContentType)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ObjectKey)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Product__3214EC072B0CD263");

            entity.ToTable("Product");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Price)
                .HasDefaultValue(100m)
                .HasColumnType("money");

            entity.HasMany(d => d.Attachments).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "AttachmentProduct",
                    r => r.HasOne<Attachment>().WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Attachmen__Attac__52593CB8"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Attachmen__Produ__5165187F"),
                    j =>
                    {
                        j.HasKey("ProductId", "AttachmentId").HasName("PK__Attachme__404E0086CC214E5E");
                        j.ToTable("AttachmentProduct");
                    });

            entity.HasMany(d => d.Tags).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "TagsProduct",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TagsProdu__TagId__5629CD9C"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TagsProdu__Produ__5535A963"),
                    j =>
                    {
                        j.HasKey("ProductId", "TagId").HasName("PK__TagsProd__625B09573230ADC5");
                        j.ToTable("TagsProduct");
                    });
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tag__3214EC07CA7F339F");

            entity.ToTable("Tag");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}