// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoolDNSWpfApp.Models;

public partial class Product
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int Count { get; set; }

    public int Discount { get; set; }

    public int Rating { get; set; }

    public int FeedbackCount { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}